import json
import uuid

# Full data from EquipmentSpecifications.dart
specifications = [
    ('Gadlee', 'GT30', {
        'power': {'value': '0.75', 'unit': 'кВт', 'label': 'Мощность'},
        'voltage': {'value': '24', 'unit': 'В', 'label': 'Напряжение'},
        'weight': {'value': '105', 'unit': 'кг', 'label': 'Вес'},
        'dimensions': {'value': '1200×750×1050', 'unit': 'мм', 'label': 'Габариты'},
        'operatorPosition': {'value': 'Ходовой', 'unit': '', 'label': 'Место для оператора'},
        'productivity': {'value': '1800', 'unit': 'кв.м/ч', 'label': 'Производительность (теоретическая)'},
        'cleaningWidth': {'value': '500', 'unit': 'мм', 'label': 'Ширина уборки'},
        'squeegeeWidth': {'value': '720', 'unit': 'мм', 'label': 'Ширина скребка'},
        'brushCount': {'value': '1', 'unit': 'шт', 'label': 'Количество щеток'},
        'brushDiameter': {'value': '500', 'unit': 'мм', 'label': 'Диаметр щетки'},
        'brushPressure': {'value': '35', 'unit': 'кг', 'label': 'Максимальное давление щеток / пада на пол'},
        'brushSpeed': {'value': '160', 'unit': 'об/мин', 'label': 'Скорость вращения щеток'},
        'cleaningType': {'value': 'Дисковый', 'unit': '', 'label': 'Тип уборочного узла'},
        'cleanWaterTank': {'value': '30', 'unit': 'л', 'label': 'Объем бака чистой воды'},
        'dirtyWaterTank': {'value': '35', 'unit': 'л', 'label': 'Объем бака грязной воды'},
        'maxClimb': {'value': '12%', 'unit': '', 'label': 'Максимальный угол подъема'},
        'powerType': {'value': 'Аккумулятор', 'unit': '', 'label': 'Тип питания'},
    }),
    ('Gadlee', 'GT50', {
        'power': {'value': '1.2', 'unit': 'кВт', 'label': 'Мощность'},
        'voltage': {'value': '24', 'unit': 'В', 'label': 'Напряжение'},
        'weight': {'value': '145', 'unit': 'кг', 'label': 'Вес'},
        'dimensions': {'value': '1350×850×1150', 'unit': 'мм', 'label': 'Габариты'},
        'operatorPosition': {'value': 'Ходовой', 'unit': '', 'label': 'Место для оператора'},
        'productivity': {'value': '2400', 'unit': 'кв.м/ч', 'label': 'Производительность (теоретическая)'},
        'cleaningWidth': {'value': '650', 'unit': 'мм', 'label': 'Ширина уборки'},
        'squeegeeWidth': {'value': '870', 'unit': 'мм', 'label': 'Ширина скребка'},
        'brushCount': {'value': '1', 'unit': 'шт', 'label': 'Количество щеток'},
        'brushDiameter': {'value': '500', 'unit': 'мм', 'label': 'Диаметр щетки'},
        'brushPressure': {'value': '40', 'unit': 'кг', 'label': 'Максимальное давление щеток / пада на пол'},
        'brushSpeed': {'value': '160', 'unit': 'об/мин', 'label': 'Скорость вращения щеток'},
        'cleaningType': {'value': 'Дисковый', 'unit': '', 'label': 'Тип уборочного узла'},
        'cleanWaterTank': {'value': '50', 'unit': 'л', 'label': 'Объем бака чистой воды'},
        'dirtyWaterTank': {'value': '55', 'unit': 'л', 'label': 'Объем бака грязной воды'},
        'maxClimb': {'value': '12%', 'unit': '', 'label': 'Максимальный угол подъема'},
        'powerType': {'value': 'Аккумулятор', 'unit': '', 'label': 'Тип питания'},
    }),
    ('Gadlee', 'GT55', {
        'power': {'value': '1.4', 'unit': 'кВт', 'label': 'Мощность'},
        'voltage': {'value': '24', 'unit': 'В', 'label': 'Напряжение'},
        'weight': {'value': '155', 'unit': 'кг', 'label': 'Вес'},
        'dimensions': {'value': '1400×900×1200', 'unit': 'мм', 'label': 'Габариты'},
        'operatorPosition': {'value': 'Ходовой', 'unit': '', 'label': 'Место для оператора'},
        'productivity': {'value': '2700', 'unit': 'кв.м/ч', 'label': 'Производительность (теоретическая)'},
        'cleaningWidth': {'value': '700', 'unit': 'мм', 'label': 'Ширина уборки'},
        'squeegeeWidth': {'value': '920', 'unit': 'мм', 'label': 'Ширина скребка'},
        'brushCount': {'value': '1', 'unit': 'шт', 'label': 'Количество щеток'},
        'brushDiameter': {'value': '550', 'unit': 'мм', 'label': 'Диаметр щетки'},
        'brushPressure': {'value': '45', 'unit': 'кг', 'label': 'Максимальное давление щеток / пада на пол'},
        'brushSpeed': {'value': '160', 'unit': 'об/мин', 'label': 'Скорость вращения щеток'},
        'cleaningType': {'value': 'Дисковый', 'unit': '', 'label': 'Тип уборочного узла'},
        'cleanWaterTank': {'value': '55', 'unit': 'л', 'label': 'Объем бака чистой воды'},
        'dirtyWaterTank': {'value': '60', 'unit': 'л', 'label': 'Объем бака грязной воды'},
        'maxClimb': {'value': '12%', 'unit': '', 'label': 'Максимальный угол подъема'},
        'powerType': {'value': 'Аккумулятор', 'unit': '', 'label': 'Тип питания'},
    }),
    ('Gadlee', 'GT70', {
        'power': {'value': '1.6', 'unit': 'кВт', 'label': 'Мощность'},
        'voltage': {'value': '24', 'unit': 'В', 'label': 'Напряжение'},
        'weight': {'value': '180', 'unit': 'кг', 'label': 'Вес'},
        'dimensions': {'value': '1450×950×1250', 'unit': 'мм', 'label': 'Габариты'},
        'operatorPosition': {'value': 'Ходовой', 'unit': '', 'label': 'Место для оператора'},
        'productivity': {'value': '3200', 'unit': 'кв.м/ч', 'label': 'Производительность (теоретическая)'},
        'cleaningWidth': {'value': '750', 'unit': 'мм', 'label': 'Ширина уборки'},
        'squeegeeWidth': {'value': '970', 'unit': 'мм', 'label': 'Ширина скребка'},
        'brushCount': {'value': '1', 'unit': 'шт', 'label': 'Количество щеток'},
        'brushDiameter': {'value': '560', 'unit': 'мм', 'label': 'Диаметр щетки'},
        'brushPressure': {'value': '50', 'unit': 'кг', 'label': 'Максимальное давление щеток / пада на пол'},
        'brushSpeed': {'value': '160', 'unit': 'об/мин', 'label': 'Скорость вращения щеток'},
        'cleaningType': {'value': 'Дисковый', 'unit': '', 'label': 'Тип уборочного узла'},
        'cleanWaterTank': {'value': '70', 'unit': 'л', 'label': 'Объем бака чистой воды'},
        'dirtyWaterTank': {'value': '75', 'unit': 'л', 'label': 'Объем бака грязной воды'},
        'maxClimb': {'value': '12%', 'unit': '', 'label': 'Максимальный угол подъема'},
        'powerType': {'value': 'Аккумулятор', 'unit': '', 'label': 'Тип питания'},
    }),
    ('Gadlee', 'GT85', {
        'power': {'value': '1.8', 'unit': 'кВт', 'label': 'Мощность'},
        'voltage': {'value': '24', 'unit': 'В', 'label': 'Напряжение'},
        'weight': {'value': '210', 'unit': 'кг', 'label': 'Вес'},
        'dimensions': {'value': '1500×1000×1300', 'unit': 'мм', 'label': 'Габариты'},
        'operatorPosition': {'value': 'Ходовой', 'unit': '', 'label': 'Место для оператора'},
        'productivity': {'value': '3800', 'unit': 'кв.м/ч', 'label': 'Производительность (теоретическая)'},
        'cleaningWidth': {'value': '850', 'unit': 'мм', 'label': 'Ширина уборки'},
        'squeegeeWidth': {'value': '1070', 'unit': 'мм', 'label': 'Ширина скребка'},
        'brushCount': {'value': '2', 'unit': 'шт', 'label': 'Количество щеток'},
        'brushDiameter': {'value': '430', 'unit': 'мм', 'label': 'Диаметр щетки'},
        'brushPressure': {'value': '55', 'unit': 'кг', 'label': 'Максимальное давление щеток / пада на пол'},
        'brushSpeed': {'value': '160', 'unit': 'об/мин', 'label': 'Скорость вращения щеток'},
        'cleaningType': {'value': 'Дисковый', 'unit': '', 'label': 'Тип уборочного узла'},
        'cleanWaterTank': {'value': '85', 'unit': 'л', 'label': 'Объем бака чистой воды'},
        'dirtyWaterTank': {'value': '90', 'unit': 'л', 'label': 'Объем бака грязной воды'},
        'maxClimb': {'value': '12%', 'unit': '', 'label': 'Максимальный угол подъема'},
        'powerType': {'value': 'Аккумулятор', 'unit': '', 'label': 'Тип питания'},
    }),
    ('Gadlee', 'GT110', {
        'power': {'value': '37', 'unit': 'кВт', 'label': 'Мощность'},
        'voltage': {'value': '380', 'unit': 'В', 'label': 'Напряжение'},
        'weight': {'value': '1450', 'unit': 'кг', 'label': 'Вес'},
        'dimensions': {'value': '1600×1200×1800', 'unit': 'мм', 'label': 'Габариты'},
        'operatorPosition': {'value': 'Райдер', 'unit': '', 'label': 'Место для оператора'},
        'productivity': {'value': '6600', 'unit': 'кв.м/ч', 'label': 'Производительность (теоретическая)'},
        'cleaningWidth': {'value': '1100', 'unit': 'мм', 'label': 'Ширина уборки'},
        'squeegeeWidth': {'value': '1320', 'unit': 'мм', 'label': 'Ширина скребка'},
        'brushCount': {'value': '2', 'unit': 'шт', 'label': 'Количество щеток'},
        'brushDiameter': {'value': '560', 'unit': 'мм', 'label': 'Диаметр щетки'},
        'brushPressure': {'value': '120', 'unit': 'кг', 'label': 'Максимальное давление щеток / пада на пол'},
        'brushSpeed': {'value': '180', 'unit': 'об/мин', 'label': 'Скорость вращения щеток'},
        'cleaningType': {'value': 'Дисковый', 'unit': '', 'label': 'Тип уборочного узла'},
        'cleanWaterTank': {'value': '110', 'unit': 'л', 'label': 'Объем бака чистой воды'},
        'dirtyWaterTank': {'value': '120', 'unit': 'л', 'label': 'Объем бака грязной воды'},
        'maxClimb': {'value': '15%', 'unit': '', 'label': 'Максимальный угол подъема'},
        'powerType': {'value': 'Аккумулятор', 'unit': '', 'label': 'Тип питания'},
    }),
    ('Gadlee', 'GT180', {
        'power': {'value': '48', 'unit': 'кВт', 'label': 'Мощность'},
        'voltage': {'value': '380', 'unit': 'В', 'label': 'Напряжение'},
        'weight': {'value': '1850', 'unit': 'кг', 'label': 'Вес'},
        'dimensions': {'value': '2200×1400×1900', 'unit': 'мм', 'label': 'Габариты'},
        'operatorPosition': {'value': 'Райдер', 'unit': '', 'label': 'Место для оператора'},
        'productivity': {'value': '10800', 'unit': 'кв.м/ч', 'label': 'Производительность (теоретическая)'},
        'cleaningWidth': {'value': '1800', 'unit': 'мм', 'label': 'Ширина уборки'},
        'squeegeeWidth': {'value': '2020', 'unit': 'мм', 'label': 'Ширина скребка'},
        'brushCount': {'value': '3', 'unit': 'шт', 'label': 'Количество щеток'},
        'brushDiameter': {'value': '600', 'unit': 'мм', 'label': 'Диаметр щетки'},
        'brushPressure': {'value': '180', 'unit': 'кг', 'label': 'Максимальное давление щеток / пада на пол'},
        'brushSpeed': {'value': '180', 'unit': 'об/мин', 'label': 'Скорость вращения щеток'},
        'cleaningType': {'value': 'Дисковый', 'unit': '', 'label': 'Тип уборочного узла'},
        'cleanWaterTank': {'value': '180', 'unit': 'л', 'label': 'Объем бака чистой воды'},
        'dirtyWaterTank': {'value': '190', 'unit': 'л', 'label': 'Объем бака грязной воды'},
        'maxClimb': {'value': '15%', 'unit': '', 'label': 'Максимальный угол подъема'},
        'powerType': {'value': 'Аккумулятор', 'unit': '', 'label': 'Тип питания'},
    }),
    ('Gadlee', 'GT260', {
        'power': {'value': '60', 'unit': 'кВт', 'label': 'Мощность'},
        'voltage': {'value': '380', 'unit': 'В', 'label': 'Напряжение'},
        'weight': {'value': '2450', 'unit': 'кг', 'label': 'Вес'},
        'dimensions': {'value': '2800×1600×2100', 'unit': 'мм', 'label': 'Габариты'},
        'operatorPosition': {'value': 'Райдер', 'unit': '', 'label': 'Место для оператора'},
        'productivity': {'value': '15600', 'unit': 'кв.м/ч', 'label': 'Производительность (теоретическая)'},
        'cleaningWidth': {'value': '2600', 'unit': 'мм', 'label': 'Ширина уборки'},
        'squeegeeWidth': {'value': '2820', 'unit': 'мм', 'label': 'Ширина скребка'},
        'brushCount': {'value': '4', 'unit': 'шт', 'label': 'Количество щеток'},
        'brushDiameter': {'value': '650', 'unit': 'мм', 'label': 'Диаметр щетки'},
        'brushPressure': {'value': '240', 'unit': 'кг', 'label': 'Максимальное давление щеток / пада на пол'},
        'brushSpeed': {'value': '180', 'unit': 'об/мин', 'label': 'Скорость вращения щеток'},
        'cleaningType': {'value': 'Дисковый', 'unit': '', 'label': 'Тип уборочного узла'},
        'cleanWaterTank': {'value': '260', 'unit': 'л', 'label': 'Объем бака чистой воды'},
        'dirtyWaterTank': {'value': '270', 'unit': 'л', 'label': 'Объем бака грязной воды'},
        'maxClimb': {'value': '15%', 'unit': '', 'label': 'Максимальный угол подъема'},
        'powerType': {'value': 'Аккумулятор', 'unit': '', 'label': 'Тип питания'},
    }),
    ('Tennant', 'T2', {
        'power': {'value': '0.6', 'unit': 'кВт', 'label': 'Мощность'},
        'voltage': {'value': '24', 'unit': 'В', 'label': 'Напряжение'},
        'weight': {'value': '92', 'unit': 'кг', 'label': 'Вес'},
        'dimensions': {'value': '1150×700×1000', 'unit': 'мм', 'label': 'Габариты'},
        'operatorPosition': {'value': 'Ходовой', 'unit': '', 'label': 'Место для оператора'},
        'productivity': {'value': '1680', 'unit': 'кв.м/ч', 'label': 'Производительность (теоретическая)'},
        'cleaningWidth': {'value': '420', 'unit': 'мм', 'label': 'Ширина уборки'},
        'squeegeeWidth': {'value': '660', 'unit': 'мм', 'label': 'Ширина скребка'},
        'brushCount': {'value': '1', 'unit': 'шт', 'label': 'Количество щеток'},
        'brushDiameter': {'value': '420', 'unit': 'мм', 'label': 'Диаметр щетки'},
        'brushPressure': {'value': '30', 'unit': 'кг', 'label': 'Максимальное давление щеток / пада на пол'},
        'brushSpeed': {'value': '170', 'unit': 'об/мин', 'label': 'Скорость вращения щеток'},
        'cleaningType': {'value': 'Дисковый', 'unit': '', 'label': 'Тип уборочного узла'},
        'cleanWaterTank': {'value': '28', 'unit': 'л', 'label': 'Объем бака чистой воды'},
        'dirtyWaterTank': {'value': '32', 'unit': 'л', 'label': 'Объем бака грязной воды'},
        'maxClimb': {'value': '10%', 'unit': '', 'label': 'Максимальный угол подъема'},
        'powerType': {'value': 'Аккумулятор', 'unit': '', 'label': 'Тип питания'},
    }),
    ('Tennant', 'T3', {
        'power': {'value': '0.75', 'unit': 'кВт', 'label': 'Мощность'},
        'voltage': {'value': '24', 'unit': 'В', 'label': 'Напряжение'},
        'weight': {'value': '105', 'unit': 'кг', 'label': 'Вес'},
        'dimensions': {'value': '1250×750×1050', 'unit': 'мм', 'label': 'Габариты'},
        'operatorPosition': {'value': 'Ходовой', 'unit': '', 'label': 'Место для оператора'},
        'productivity': {'value': '2150', 'unit': 'кв.м/ч', 'label': 'Производительность (теоретическая)'},
        'cleaningWidth': {'value': '500', 'unit': 'мм', 'label': 'Ширина уборки'},
        'squeegeeWidth': {'value': '740', 'unit': 'мм', 'label': 'Ширина скребка'},
        'brushCount': {'value': '1', 'unit': 'шт', 'label': 'Количество щеток'},
        'brushDiameter': {'value': '500', 'unit': 'мм', 'label': 'Диаметр щетки'},
        'brushPressure': {'value': '35', 'unit': 'кг', 'label': 'Максимальное давление щеток / пада на пол'},
        'brushSpeed': {'value': '170', 'unit': 'об/мин', 'label': 'Скорость вращения щеток'},
        'cleaningType': {'value': 'Дисковый', 'unit': '', 'label': 'Тип уборочного узла'},
        'cleanWaterTank': {'value': '43', 'unit': 'л', 'label': 'Объем бака чистой воды'},
        'dirtyWaterTank': {'value': '47', 'unit': 'л', 'label': 'Объем бака грязной воды'},
        'maxClimb': {'value': '10%', 'unit': '', 'label': 'Максимальный угол подъема'},
        'powerType': {'value': 'Аккумулятор', 'unit': '', 'label': 'Тип питания'},
    }),
    ('Tennant', 'T300', {
        'power': {'value': '0.75', 'unit': 'кВт', 'label': 'Мощность'},
        'voltage': {'value': '24', 'unit': 'В', 'label': 'Напряжение'},
        'weight': {'value': '115', 'unit': 'кг', 'label': 'Вес'},
        'dimensions': {'value': '1300×750×1050', 'unit': 'мм', 'label': 'Габариты'},
        'operatorPosition': {'value': 'Ходовой', 'unit': '', 'label': 'Место для оператора'},
        'productivity': {'value': '2100', 'unit': 'кв.м/ч', 'label': 'Производительность (теоретическая)'},
        'cleaningWidth': {'value': '500', 'unit': 'мм', 'label': 'Ширина уборки'},
        'squeegeeWidth': {'value': '740', 'unit': 'мм', 'label': 'Ширина скребка'},
        'brushCount': {'value': '1', 'unit': 'шт', 'label': 'Количество щеток'},
        'brushDiameter': {'value': '500', 'unit': 'мм', 'label': 'Диаметр щетки'},
        'brushPressure': {'value': '35', 'unit': 'кг', 'label': 'Максимальное давление щеток / пада на пол'},
        'brushSpeed': {'value': '170', 'unit': 'об/мин', 'label': 'Скорость вращения щеток'},
        'cleaningType': {'value': 'Дисковый', 'unit': '', 'label': 'Тип уборочного узла'},
        'cleanWaterTank': {'value': '68', 'unit': 'л', 'label': 'Объем бака чистой воды'},
        'dirtyWaterTank': {'value': '72', 'unit': 'л', 'label': 'Объем бака грязной воды'},
        'maxClimb': {'value': '10%', 'unit': '', 'label': 'Максимальный угол подъема'},
        'powerType': {'value': 'Аккумулятор', 'unit': '', 'label': 'Тип питания'},
    }),
    ('Tennant', 'T5', {
        'power': {'value': '1.2', 'unit': 'кВт', 'label': 'Мощность'},
        'voltage': {'value': '24', 'unit': 'В', 'label': 'Напряжение'},
        'weight': {'value': '195', 'unit': 'кг', 'label': 'Вес'},
        'dimensions': {'value': '1400×900×1200', 'unit': 'мм', 'label': 'Габариты'},
        'operatorPosition': {'value': 'Ходовой', 'unit': '', 'label': 'Место для оператора'},
        'productivity': {'value': '3240', 'unit': 'кв.м/ч', 'label': 'Производительность (теоретическая)'},
        'cleaningWidth': {'value': '700', 'unit': 'мм', 'label': 'Ширина уборки'},
        'squeegeeWidth': {'value': '940', 'unit': 'мм', 'label': 'Ширина скребка'},
        'brushCount': {'value': '1', 'unit': 'шт', 'label': 'Количество щеток'},
        'brushDiameter': {'value': '560', 'unit': 'мм', 'label': 'Диаметр щетки'},
        'brushPressure': {'value': '50', 'unit': 'кг', 'label': 'Максимальное давление щеток / пада на пол'},
        'brushSpeed': {'value': '165', 'unit': 'об/мин', 'label': 'Скорость вращения щеток'},
        'cleaningType': {'value': 'Дисковый', 'unit': '', 'label': 'Тип уборочного узла'},
        'cleanWaterTank': {'value': '80', 'unit': 'л', 'label': 'Объем бака чистой воды'},
        'dirtyWaterTank': {'value': '83', 'unit': 'л', 'label': 'Объем бака грязной воды'},
        'maxClimb': {'value': '12%', 'unit': '', 'label': 'Максимальный угол подъема'},
        'powerType': {'value': 'Аккумулятор', 'unit': '', 'label': 'Тип питания'},
    }),
    ('Tennant', 'T7', {
        'power': {'value': '1.5', 'unit': 'кВт', 'label': 'Мощность'},
        'voltage': {'value': '36', 'unit': 'В', 'label': 'Напряжение'},
        'weight': {'value': '220', 'unit': 'кг', 'label': 'Вес'},
        'dimensions': {'value': '1500×950×1250', 'unit': 'мм', 'label': 'Габариты'},
        'operatorPosition': {'value': 'Ходовой', 'unit': '', 'label': 'Место для оператора'},
        'productivity': {'value': '3800', 'unit': 'кв.м/ч', 'label': 'Производительность (теоретическая)'},
        'cleaningWidth': {'value': '820', 'unit': 'мм', 'label': 'Ширина уборки'},
        'squeegeeWidth': {'value': '1060', 'unit': 'мм', 'label': 'Ширина скребка'},
        'brushCount': {'value': '2', 'unit': 'шт', 'label': 'Количество щеток'},
        'brushDiameter': {'value': '410', 'unit': 'мм', 'label': 'Диаметр щетки'},
        'brushPressure': {'value': '60', 'unit': 'кг', 'label': 'Максимальное давление щеток / пада на пол'},
        'brushSpeed': {'value': '180', 'unit': 'об/мин', 'label': 'Скорость вращения щеток'},
        'cleaningType': {'value': 'Дисковый', 'unit': '', 'label': 'Тип уборочного узла'},
        'cleanWaterTank': {'value': '115', 'unit': 'л', 'label': 'Объем бака чистой воды'},
        'dirtyWaterTank': {'value': '123', 'unit': 'л', 'label': 'Объем бака грязной воды'},
        'maxClimb': {'value': '12%', 'unit': '', 'label': 'Максимальный угол подъема'},
        'powerType': {'value': 'Аккумулятор', 'unit': '', 'label': 'Тип питания'},
    }),
    ('Tennant', 'T12', {
        'power': {'value': '28', 'unit': 'кВт', 'label': 'Мощность'},
        'voltage': {'value': '380', 'unit': 'В', 'label': 'Напряжение'},
        'weight': {'value': '1250', 'unit': 'кг', 'label': 'Вес'},
        'dimensions': {'value': '2050×1350×1650', 'unit': 'мм', 'label': 'Габариты'},
        'operatorPosition': {'value': 'Райдер', 'unit': '', 'label': 'Место для оператора'},
        'productivity': {'value': '7440', 'unit': 'кв.м/ч', 'label': 'Производительность (теоретическая)'},
        'cleaningWidth': {'value': '1240', 'unit': 'мм', 'label': 'Ширина уборки'},
        'squeegeeWidth': {'value': '1480', 'unit': 'мм', 'label': 'Ширина скребка'},
        'brushCount': {'value': '2', 'unit': 'шт', 'label': 'Количество щеток'},
        'brushDiameter': {'value': '620', 'unit': 'мм', 'label': 'Диаметр щетки'},
        'brushPressure': {'value': '110', 'unit': 'кг', 'label': 'Максимальное давление щеток / пада на пол'},
        'brushSpeed': {'value': '190', 'unit': 'об/мин', 'label': 'Скорость вращения щеток'},
        'cleaningType': {'value': 'Дисковый', 'unit': '', 'label': 'Тип уборочного узла'},
        'cleanWaterTank': {'value': '170', 'unit': 'л', 'label': 'Объем бака чистой воды'},
        'dirtyWaterTank': {'value': '180', 'unit': 'л', 'label': 'Объем бака грязной воды'},
        'maxClimb': {'value': '14%', 'unit': '', 'label': 'Максимальный угол подъема'},
        'powerType': {'value': 'Аккумулятор', 'unit': '', 'label': 'Тип питания'},
    }),
    ('IPC', 'CT15', {
        'weight': {'value': '38', 'unit': 'кг', 'label': 'Вес'},
        'productivity': {'value': '1300', 'unit': 'кв.м/ч', 'label': 'Производительность (теоретическая)'},
        'cleaningWidth': {'value': '350', 'unit': 'мм', 'label': 'Ширина уборки'},
        'cleanWaterTank': {'value': '15', 'unit': 'л', 'label': 'Объем бака чистой воды'},
        'dirtyWaterTank': {'value': '19', 'unit': 'л', 'label': 'Объем бака грязной воды'},
    }),
    ('IPC', 'CT30', {
        'weight': {'value': '53', 'unit': 'кг', 'label': 'Вес'},
        'productivity': {'value': '1670', 'unit': 'кв.м/ч', 'label': 'Производительность (практическая)'},
        'cleaningWidth': {'value': '450', 'unit': 'мм', 'label': 'Ширина уборки'},
        'cleanWaterTank': {'value': '28', 'unit': 'л', 'label': 'Объем бака чистой воды'},
        'dirtyWaterTank': {'value': '30', 'unit': 'л', 'label': 'Объем бака грязной воды'},
    }),
    ('IPC', 'CT40', {
        'weight': {'value': '67', 'unit': 'кг', 'label': 'Вес'},
        'productivity': {'value': '1750', 'unit': 'кв.м/ч', 'label': 'Производительность (практическая)'},
        'cleaningWidth': {'value': '500', 'unit': 'мм', 'label': 'Ширина уборки'},
        'cleanWaterTank': {'value': '40', 'unit': 'л', 'label': 'Объем бака чистой воды'},
        'dirtyWaterTank': {'value': '50', 'unit': 'л', 'label': 'Объем бака грязной воды'},
    }),
    ('IPC', 'CT70', {
        'weight': {'value': '90', 'unit': 'кг', 'label': 'Вес'},
        'productivity': {'value': '2475', 'unit': 'кв.м/ч', 'label': 'Производительность (практическая)'},
        'cleaningWidth': {'value': '700', 'unit': 'мм', 'label': 'Ширина уборки'},
        'cleanWaterTank': {'value': '70', 'unit': 'л', 'label': 'Объем бака чистой воды'},
        'dirtyWaterTank': {'value': '75', 'unit': 'л', 'label': 'Объем бака грязной воды'},
    }),
]

sql_template = "INSERT INTO equipment_models (id, supplier_id, manufacturer, model, specifications) VALUES ('{}', (SELECT id FROM users WHERE role = 'super_admin' LIMIT 1), '{}', '{}', '{}');"

with open('migrate_models.sql', 'w', encoding='utf-8') as f:
    for manufacturer, model, specs in specifications:
        model_id = str(uuid.uuid4())
        specs_json = json.dumps(specs, ensure_ascii=False).replace("'", "''")
        f.write(sql_template.format(model_id, manufacturer, model, specs_json) + "\n")
print("Done generating migrate_models.sql")
